# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    tags: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew packageDebug 

    - name: Upload package to github packages
      run: G=./app/build.gradle && export VERSION=$(grep -oP 'versionName "\K(.*?)(?=")' $G) && export APPNAME=$(grep -oP 'applicationId ".*' $G |sed 's/.*\.\([^\.]\+\)"/\1/g') && export APK=./app/build/outputs/apk/debug/app-debug.apk && export FNAME=${APPNAME}-${VERSION}.apk && env && mv $APK $FNAME && hub release create -a $FNAME -m $FNAME $VERSION
